# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/utils_test',
                'doc_host': 'https://k111git.github.io',
                'git_url': 'https://github.com/k111git/utils_test',
                'lib_path': 'utils_test'},
  'syms': {'utils_test.core': {'utils_test.core.foo': ('core.html#foo', 'utils_test/core.py')}}}
